### ISSUE TITLE
Error with Makefile..sed

### ISSUE THREAD

**Issue by afernandezody** [cjcoats/ioapi-3.2#7]
Hello,
I'm trying to build v3.2-20200828 (for CMAQ purposes) in a CentOS8 system. I was able to build both the ioapi and m3tools components (libioapi.a and the m3 tools are are created). However, the funky behavior happens when I try to build everything from the top-tree directory, which is what the CMAQ UG recommends as it's producing the following output:  
```
$ sudo make configure
(cd /opt/ioapi-3.2/ioapi   ;  sed -e 's|IOAPI_BASE|/opt/ioapi-3.2|' -e 's|LIBINSTALL||' -e 's|BININSTALL||' -e 's|IOAPI_DEFS||' -e 's|NCFLIBS|-L/opt/netcdf/lib -lnetcdff -L/opt/netcdf/lib -lnetcdf|' -e 's|MAKEINCLUDE|include /opt/ioapi-3.2/ioapi/Makeinclude|' -e 's|PVMINCLUDE|include  |' < Makefile..sed > Makefile )
/bin/sh: Makefile..sed: No such file or directory
make: *** [Makefile:211: configure] Error 1
```
I don't understand what the last part of the command is supposed to do and therefore why it's generating the error. [NOTE: This is the 1st time that I try to build both I/O API & CMAQ so I'm not 100% sure if I even need to do this or building from the ioapi & m3tools branches suffices to build CMAQ]. Thanks.

**Comment by cjcoats** [comment]
Sorry it's taken a while to reply:  I've been out of town.

The build-instructions for the I/O API are here: https://cjcoats.github.io/ioapi/AVAIL.html#build

Ignore what the CMAQ instructions say:  they aren't the authors, and don't always know
what they're doing:  copy the ioapi/Makefile.nocpl to ioapi/Makefile, and similarly for
m3tools.  Then edit the Makefiles so that they has the right installation-dorectory and the
right version of netCDF-libraries (-lnetcdff -lnetcdf for netCDF-4 or -lnetcdf for netCDF3),
and then do setenv BIN ... and make in each of these directories.

At their request, I tried to put in that "single-tree" thing, but in my non-humble opinion it is
NOT the way to go; do the one-$BIN-at-a-time way recommended in the build-instructions
linked above (that procedure attempts to use the sed command to do the edits required,
and then runs make in each of these directories.

In what you're seeing, the Makefile..sed should be Makefile.sed (just one period, not two).

-- Carlie

________________________________
From: afernandezody ***@***.***>
Sent: Friday, June 25, 2021 10:53 AM
To: cjcoats/ioapi-3.2 ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [cjcoats/ioapi-3.2] Error with Makefile..sed (#7)


Hello,
I'm trying to build v3.2-20200828 (for CMAQ purposes) in a CentOS8 system. I was able to build both the ioapi and m3tools components (libioapi.a and the m3 tools are are created). However, the funky behavior happens when I try to build everything from the top-tree directory, which is what the CMAQ UG recommends as it's producing the following output:

$ sudo make configure
(cd /opt/ioapi-3.2/ioapi   ;  sed -e 's|IOAPI_BASE|/opt/ioapi-3.2|' -e 's|LIBINSTALL||' -e 's|BININSTALL||' -e 's|IOAPI_DEFS||' -e 's|NCFLIBS|-L/opt/netcdf/lib -lnetcdff -L/opt/netcdf/lib -lnetcdf|' -e 's|MAKEINCLUDE|include /opt/ioapi-3.2/ioapi/Makeinclude|' -e 's|PVMINCLUDE|include  |' < Makefile..sed > Makefile )
/bin/sh: Makefile..sed: No such file or directory
make: *** [Makefile:211: configure] Error 1


I don't understand what the last part of the command is supposed to do and therefore why it's generating the error. [NOTE: This is the 1st time that I try to build both I/O API & CMAQ so I'm not 100% sure if I even need to do this or building from the ioapi & m3tools branches suffices to build CMAQ]. Thanks.

**Comment by afernandezody** [comment]
Hi @**cjcoats**,
What you're suggesting is how I proceeded. I still haven't compiled CMAQ (still working in a couple of things unrelated to ioapi-3.2) so I won't be 100% sure until trying the compilation itself. I don't know why the script is taking a double period, but that is for the single-tree compilation so it might not be even relevant after all. Will close the ticket if everything goes well. Thanks.
